const CLASS_TEMPLATE = [
  ["Conociendo tu voz","voz","Aprender qué es la voz, cómo se produce y comenzar a escuchar el propio instrumento."],
  ["Postura y alineación corporal","postura","Establecer una postura alineada, cómoda y preparada para cantar."],
  ["Respiración para cantar","respiracion","Comprender y practicar la respiración aplicada al canto."],
  ["Control del aire","respiracion","Aprender a dosificar y estabilizar el flujo de aire."],
  ["Relajación y eliminación de tensión","relajacion","Identificar y liberar tensiones que interfieren con la emisión."],
  ["Cómo se produce la voz","voz","Comprender el proceso básico de producción vocal."],
  ["Cuerdas vocales y emisión","emision","Relacionar la producción del sonido con una emisión coordinada."],
  ["Resonancia","resonancia","Explorar sensaciones de resonancia y claridad vocal."],
  ["Articulación y vocales","articulacion","Trabajar vocales y movimientos articulatorios para una emisión clara."],
  ["Dicción","diccion","Mejorar claridad y precisión de las palabras al cantar."],
  ["Oído musical","oido","Comenzar el entrenamiento para reconocer y reproducir diferencias de altura."],
  ["Graves y agudos","extension","Explorar registros de altura sin forzar la voz."],
  ["Afinación","afinacion","Desarrollar la capacidad de igualar y sostener notas."],
  ["Pulso y ritmo","ritmo","Comprender pulso, tempo y coordinación rítmica."],
  ["Primeras vocalizaciones","vocalizacion","Integrar respiración, emisión y afinación mediante vocalizaciones."],
  ["Calentamiento vocal completo","calentamiento","Construir una rutina segura de preparación vocal."],
  ["Control de la voz","control","Mejorar estabilidad, coordinación y control."],
  ["Proyección sin forzar","proyeccion","Aprender a proyectar con coordinación y sin empujar."],
  ["Respiración + voz + afinación","integracion","Integrar los fundamentos trabajados durante el mes."],
  ["Evaluación completa del Mes 1","evaluacion","Evaluar fundamentos y determinar puntos de refuerzo."],
  ["Voz de pecho","registros","Explorar la coordinación de pecho con seguridad."],
  ["Voz de cabeza","registros","Explorar la coordinación de cabeza y sus sensaciones."],
  ["Falsete","registros","Comprender y practicar el falsete sin forzar."],
  ["Transición de registros","registros","Trabajar cambios entre zonas vocales."],
  ["Voz mixta","mixta","Introducir la coordinación de mezcla de registros."],
  ["Extensión vocal","extension","Ampliar progresivamente el rango dentro de límites cómodos."],
  ["Graves y zona media","extension","Estabilizar graves y zona media."],
  ["Agudos con seguridad","agudos","Trabajar alturas superiores sin empujar."],
  ["Resonancia y colocación","resonancia","Refinar sensaciones de resonancia y colocación."],
  ["Control y estabilidad","control","Desarrollar consistencia de emisión."],
  ["Dinámica y volumen","dinamica","Trabajar cambios de intensidad controlados."],
  ["Legato","musicalidad","Conectar notas y frases con continuidad."],
  ["Staccato","musicalidad","Practicar ataques breves y controlados."],
  ["Ataques y finales","emision","Mejorar inicio y cierre de sonidos."],
  ["Escalas","musicalidad","Aplicar escalas al entrenamiento vocal."],
  ["Arpegios","musicalidad","Aplicar arpegios para coordinación y oído."],
  ["Intervalos","oido","Reconocer y reproducir distancias entre notas."],
  ["Afinación avanzada","afinacion","Aumentar precisión y estabilidad de afinación."],
  ["Respiración aplicada","respiracion","Usar la respiración dentro de frases musicales."],
  ["Musicalidad y fraseo","musicalidad","Comenzar a tomar decisiones musicales conscientes."],
  ["Interpretación","interpretacion","Trabajar intención y comunicación."],
  ["Emoción y expresión","interpretacion","Relacionar emoción, intención y expresión vocal."],
  ["Fraseo","interpretacion","Construir frases con dirección musical."],
  ["Dinámica aplicada","dinamica","Aplicar contrastes dinámicos a material musical."],
  ["Respiración musical","respiracion","Planificar respiraciones dentro de una canción."],
  ["Canto con acompañamiento","repertorio","Coordinar voz con acompañamiento."],
  ["Canto con pista","repertorio","Practicar con una pista manteniendo pulso y melodía."],
  ["Análisis de canciones","repertorio","Analizar estructura, tonalidad, melodía y dificultades."],
  ["Tonalidades y adaptación","repertorio","Comprender cómo una tonalidad afecta la comodidad vocal."],
  ["Melodía y ritmo","musicalidad","Integrar melodía y ritmo en material completo."],
  ["Grabación y autoescucha","grabacion","Aprender a grabarse y escuchar críticamente."],
  ["Análisis de grabaciones","grabacion","Identificar fortalezas y puntos de trabajo en grabaciones."],
  ["Micrófono: distancia y posición","microfono","Conocer principios básicos de uso del micrófono."],
  ["Micrófono: volumen y dinámica","microfono","Aplicar dinámica y distancia al micrófono."],
  ["Presencia y confianza","presencia","Prepararse para cantar frente a otras personas."],
  ["Comunicación con el público","presencia","Trabajar intención y conexión."],
  ["Canción completa: preparación","repertorio","Preparar una canción siguiendo un proceso completo."],
  ["Canción completa: práctica","repertorio","Practicar una canción completa por etapas."],
  ["Presentación final","evaluacion","Preparar la presentación final del programa."],
  ["Evaluación vocal final","evaluacion","Evaluar técnica, oído, ritmo y musicalidad."],
  ["Examen final Canto Forever","evaluacion","Integrar teoría, oído, técnica, interpretación y canción completa."]
];

const CLASSES = CLASS_TEMPLATE.map((x,i)=>({
  id:i+1, month:i<20?1:i<40?2:3, week:Math.floor(i/5)+1, day:(i%5)+1,
  title:x[0], category:x[1], objective:x[2],
  duration:120,
  theory:[
    `En esta clase vamos a trabajar ${x[0].toLowerCase()}.`,
    `La profesora te explicará el concepto desde la perspectiva de un cantante y lo conectará con la práctica.`,
    `Aprenderás qué debes observar, qué errores son frecuentes y cómo comprobar tu propio trabajo.`
  ],
  teacherScript:`Bienvenido a la clase ${i+1}. Hoy vamos a trabajar ${x[0].toLowerCase()}. No buscamos perfección inmediata: buscamos comprender, practicar y comprobar lo aprendido.`,
  exercises:[
    {name:`Preparación — ${x[0]}`,minutes:8,instructions:`Adopta una postura cómoda, respira con naturalidad y prepara la voz sin forzar. Sigue las indicaciones de la profesora.`},
    {name:`Ejercicio principal`,minutes:12,instructions:`Realiza el ejercicio lentamente. Haz las repeticiones indicadas y descansa si aparece fatiga o molestia.`},
    {name:`Aplicación`,minutes:10,instructions:`Lleva el concepto a una vocalización o frase breve. Escucha lo que ocurre y anota cualquier dificultad.`}
  ],
  questions:[
    `¿Cuál es el objetivo principal de esta clase?`,
    `¿Qué sensación o resultado deberías observar durante la práctica?`
  ],
  evaluation:[`Comprendí el concepto`,`Pude realizar el ejercicio`,`Identifiqué una dificultad`,`Sé qué practicar después`],
  homework:`Repite el ejercicio principal durante 10–15 minutos, sin forzar la voz, y registra en el cuaderno qué sentiste y qué te costó.`,
  summary:`Hoy trabajaste ${x[0].toLowerCase()}. Guarda tus observaciones y utiliza el sistema de repaso si necesitas reforzarlo.`
}));
